authors:
  sumanth:
    name: Y Sai Sumanth
    description: Data Scientist
    avatar: https://avatars.githubusercontent.com/u/29101759?s=400&u=8c690a955169dee3125d1f2ef55961fbe842e8b5&v=4
  yeshwanth:
    name: Y Yeshwanth
    description: Data Scientist
    avatar: https://avatars.githubusercontent.com/u/3656100?v=4
    url: https://github.com/sizhky